services:
  yh38-db:
    image: postgres:14.19
    container_name: yh38-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: yh38_user
      POSTGRES_PASSWORD: "yh38_pass"
      POSTGRES_DB: yh38_local
    ports:
      - "5432:5432"
    volumes:
      - yh38_pgdata:/var/lib/postgresql/data
    networks:
      - yh38-net

  yh38-api:
    image: node:22.21.1
    container_name: yh38-api
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./be:/app
    command: sh -c "npm install && npm start"
    environment:
      PORT: "4000"
      PGHOST: "yh38-db"
      PGPORT: "5432"
      PGUSER: "yh38_user"
      PGPASSWORD: "yh38_pass"
      PGDATABASE: "yh38_local"

      DATABASE_URL: "postgres://yh38_user:yh38_pass@yh38-db:5432/yh38_local"

      ALLOWED_ORIGINS: "http://localhost:5173"
      JWT_SECRET: "yh38-super-secret"
    ports:
      - "4000:4000"
    depends_on:
      - yh38-db
    networks:
      - yh38-net

  yh38-fe:
    image: node:22.21.1
    container_name: yh38-fe
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./fe:/app
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_BASE_URL: "http://localhost:4000/api"
    ports:
      - "5173:5173"
      - "5174:5174"
    depends_on:
      - yh38-api
    networks:
      - yh38-net

volumes:
  yh38_pgdata:

networks:
  yh38-net: